name: Cloudnet Deploy

on:
  workflow_call:
    inputs:
      target:
        type: string
        required: true
      hostname:
        type: string
        required: true
      user:
        type: string
        required: false
        default: "deploy"
      fingerprint:
        type: string
        required: true
      destination:
        type: string
        required: true
    secrets:
      deploy_key:
        required: true

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2

    - name: Setup PHP 7.4
      uses: shivammathur/setup-php@v2
      with:
        php-version: '7.4'

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v2
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
      
    - name: Install dependencies
      run: composer install --no-progress

    - name: Activate ssh-agent with deploy key
      run: |
        eval "$( ssh-agent )"
        ssh-add - <<< "${{ secrets.DEPLOY_KEY }}"
        printenv|egrep -e SSH_AUTH_SOCK -e SSH_AGENT_PID >> $GITHUB_ENV
        mkdir ~/.ssh
        echo "${{ inputs.FINGERPRINT }}" >> ~/.ssh/known_hosts

    - name: Prepare target for deploy
      run: |
        ssh ${{ inputs.USER }}@${{ inputs.HOSTNAME }} " \
          rm -rf ${{ inputs.DESTINATION }}/release.old; \
          rm -rf ${{ inputs.DESTINATION }}/release.new; \
          mkdir -p ${{ inputs.DESTINATION }}/release; \
          mkdir ${{ inputs.DESTINATION }}/release.new"

    - name: rsync build to Cloudnet
      run: rsync -av --delete-after --exclude .git ${GITHUB_WORKSPACE}/. ${{ inputs.USER }}@${{ inputs.HOSTNAME }}:${{ inputs.DESTINATION }}/release.new/.

    - name: Create symlinks and run DB update
      run: |
        ssh deploy@${{ inputs.HOSTNAME }} " \
          ln -s ../shared/.env ${{ inputs.DESTINATION }}/release.new && \
          ( sudo systemctl stop nginx || true ) && \
          mv ${{ inputs.DESTINATION }}/release ${{ inputs.DESTINATION }}/release.old && \
          mv ${{ inputs.DESTINATION }}/release.new ${{ inputs.DESTINATION }}/release && \
          cd ${{ inputs.DESTINATION }}/release && \
          bin/console doctrine:schema:update --force && \
          sudo systemctl start nginx"

